# Generated by Django 5.2.6 on 2025-10-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('InventarioView', 'Permiso para ver el inventario'), ('CrearAutomovilView', 'Permiso para crear automóviles'), ('EditarAutomovilView', 'Permiso para editar automóviles'), ('EliminarAutomovilView', 'Permiso para eliminar automóviles'), ('DetalleAutomovilView', 'Permiso para ver el detalle de automóviles')]},
        ),
    ]
