# Generated by Django 5.2.6 on 2025-10-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('InventarioView', 'Permiso para ver el inventario'), ('CrearAutomovilView', 'Permiso para crear automóviles'), ('EditarAutomovilView', 'Permiso para editar automóviles'), ('EliminarAutomovilView', 'Permiso para eliminar automóviles'), ('DetalleAutomovilView', 'Permiso para ver el detalle de automóviles'), ('PanelAdminView', 'Permiso para ver el panel de administración'), ('CrearUsuario', 'Permiso para crear usuarios desde panel admin'), ('EditarUsuario', 'Permiso para editar usuarios desde panel admin'), ('EliminarUsuario', 'Permiso para eliminar usuarios desde panel admin')]},
        ),
    ]
