# Generated by Django 5.2.6 on 2025-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20, verbose_name='Estado del vehículo'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible (legacy)'),
        ),
    ]
