# Generated by Django 5.2.6 on 2025-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_automovil_estado_alter_automovil_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='automovil',
            name='estado',
        ),
        migrations.AddField(
            model_name='automovil',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
