# Generated by Django 5.2.6 on 2025-11-25 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesTecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(help_text='Ej: 2.0L Turbo 4 cilindros', max_length=100)),
                ('transmision', models.CharField(help_text='Ej: Automática 8 velocidades', max_length=50)),
                ('combustible', models.CharField(help_text='Ej: Gasolina, Diésel, Eléctrico', max_length=50)),
                ('traccion', models.CharField(blank=True, help_text='Ej: 4x4, AWD, FWD', max_length=50)),
                ('cilindrada', models.CharField(blank=True, help_text='Ej: 2000cc', max_length=50)),
                ('potencia', models.CharField(blank=True, help_text='Ej: 250 HP', max_length=50)),
            ],
            options={
                'verbose_name': 'Especificaciones Técnicas',
                'verbose_name_plural': 'Especificaciones Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ej: Corolla, Mustang, Serie 3', max_length=100)),
                ('anio', models.IntegerField(help_text='Año de fabricación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('kilometraje', models.IntegerField(blank=True, help_text='Kilometraje actual', null=True)),
                ('num_puertas', models.IntegerField(blank=True, help_text='Número de puertas', null=True)),
                ('num_pasajeros', models.IntegerField(blank=True, help_text='Capacidad de pasajeros', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del vehículo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('condicion', models.ManyToManyField(help_text='Nuevo, Usado, Seminuevo, etc.', related_name='vehiculos', to='autos.condicion')),
                ('especificaciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='autos.especificacionestecnicas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='autos.marca')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
