# Generated by Django 5.2.6 on 2025-11-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='especificaciones',
        ),
    ]
