# Generated by Django 5.2.6 on 2025-11-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_remove_vehiculo_especificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiones', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Especificaciones Técnicas',
                'verbose_name_plural': 'Especificaciones Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='especificacionestecnicas',
            options={},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='autos.categoria'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='detalles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='autos.detallevehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='vehiculos', to='autos.etiqueta'),
        ),
    ]
