# Generated by Django 5.2.6 on 2025-11-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_categoria_detallevehiculo_etiqueta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspecificacionesTecnicas',
        ),
        migrations.AlterModelOptions(
            name='detallevehiculo',
            options={'verbose_name': 'Detalles del Vehículo', 'verbose_name_plural': 'Detalles del Vehículo'},
        ),
    ]
