# Generated by Django 5.2.7 on 2025-11-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_delete_especificacionestecnicas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiqueta',
            new_name='Atributo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='etiquetas',
            new_name='atributos',
        ),
    ]
